version: "3.9"

services:
  crawler_service:
    build: ./crawler
    container_name: 8_crawler
    ports:
      - "8000:8000"

  mysql_service:
    build: ./mysql
    container_name: 8_mysql
    ports:
      - "6603:3306"