version: "3.9"

services:
  web_service:
    build: ./web
    container_name: 8_web
    ports:
      - "8888:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - 8_network

  crawler_service:
    build: ./crawler
    container_name: 8_crawler
    ports:
      - "8000:8000"
    volumes:
      - ./crawler:/api
    networks:
      - 8_network

  api_service:
    build: ./api
    container_name: 8_api
    ports:
      - "9000:9000"
    networks:
      - 8_network

  mysql_service:
    build: ./mysql
    container_name: 8_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: psw123
    networks:
      - 8_network

networks:
  8_network:
    driver: bridge