version: "3.9"

services:
  web_service:
    build: ./web
    container_name: 8_web
    ports:
      - "8888:8888"
    volumes:
      - ./web:/usr/share/nginx/html
    links:
      - api_service
    depends_on:
      - api_service

  crawler_service:
    build: ./crawler
    container_name: 8_crawler
    ports:
      - "8000:8000"
    volumes:
      - ./crawler:/api
    links:
      - api_service
    depends_on:
      - api_service

  api_service:
    build: ./api
    container_name: 8_api
    ports:
      - "9000:9000"
    links:
      - mysql_service
    depends_on:
      - mysql_service

  mysql_service:
    build: ./mysql
    container_name: 8_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: psw123
